### ISSUE TITLE
How to reverse gender information?

### ISSUE THREAD

**Issue by jwalantsoneji** [namsor/gendreapp#1]
Great tool! Works pretty well. Show some non categorised but no wrong assignments. Thanks!

Is there any way to reverse this to not to have gender information in names?

**Comment by namsor** [comment]
Hey, thanks for your kind comment! Yes, this process was improved in v0.0.5 deployed via F-Droid.

To reverse the gender information you need to 
- stop Gender service, 
- go to Settings->Wipe with Title format None,
- Start the service : that will remove Titles matching the Gender formats (Mr.,Ms.,etc. as well as icons Heart, Male, Female etc.)
