### ISSUE TITLE
Once installed there is no way to reverse what has been done

### ISSUE THREAD

**Issue by jimheem** [namsor/gendreapp#2]
There should be a method to reverse what was done, or at least allow the option to do a complete rescan of items already scanned to allow changing the field. Also, having hearts as the default option for females may not be the best idea when a guys wife looks through his phone and sees hearts on all the women. Just sayin.

**Comment by namsor** [comment]
Hi Jumheem,

Hey, thanks for your comment! Will help us make next version better. Reversal process was improved in v0.0.5 (ex. deployed via F-Droid).

To reverse the gender information you need to

```
stop Gender service,
go to Settings->Wipe with Title format None,
Start the service : that will remove Titles matching the Gender formats (Mr.,Ms.,etc. as well as icons Heart, Male, Female etc.)
```

You can also select WIPE and different format (like Gender or Mr./Ms.) to do a complete rescan and set a different option for Title information. 

Cheers,
E.

**Comment by jimheem** [comment]
Hi - I had tried this method already, and it does not work. I even tried uninstalling the app and reinstalling, it still refuses to wipe or change anything in the title field.

**Comment by namsor** [comment]
Are you sure you have version 0.0.5?
https://f-droid.org/repository/browse/?fdfilter=gendre&fdid=com.namsor.api.samples.gendre
Please try again with : 
- Settings : Wipe=True, Gender style=None,
- Start the service
  If that doesn't work, we'll find a way to get more debugging info.

**Comment by jimheem** [comment]
Hi - I do have the latest version from f-droid. I also triple checked that I have wipe on and style none - matter of fact I've even done it with the other styles. I find that if I manually edit a contact to remove the heart or gender symbol, the app will modify it, but it will not modify anything that has anything in the title section. the display on gendre will show only the number of contacts that I have manually edited. 

A thought I had was maybe I was getting rate-limited on http requests, so I stuck a sniffer on it to find that it is only making http requests for the contacts that have nothing in the title field.

http://i.imgur.com/yIDK9WG.png
http://www.imgur.com/x3AqzIT.png

**Comment by jimheem** [comment]
ok - update. I removed my work contacts that had their own account in "Touchdown" app. once I removed that account the action started working.  Strange thing is that the first run though worked fine with that account included. It just refused to wipe anything if that account was enabled

**Comment by namsor** [comment]
Great ! Thanks again for your comments.
