### ISSUE TITLE
API suggestion

### ISSUE THREAD

**Issue by ghost** [namsor/gendreapp#3]
Hi,

This suggestion relates to the API, is this the wrong place to make a suggestion? 

My suggestion: 

Share the guessed region for the name as well as the gender. 

For my intended application, knowing the likely country of origin of the name and even better the probability of correctness/confidence would be awesome

**Comment by namsor** [comment]
Hi Synthapy,

Thank you for the suggestion. We publish backtests on the overall accuracy of predicting gender from personal names here http://namesorts.com/api/ 

Also we've designed the gender scale metric range (-1..+1) as a synthetic indicator of gender (with range -1 is certainly Male, -0.1 to 0.1 is Unknown, +1 is certainly Female). You are right that we could expose an additional indicator of confidence. We will look into this.

As for the country of origin of the name, we're thinking of opening a separate and dedicated API. What is your usecase and timeline? In case this is something you would like to discuss privately, contact@namsor.com

**Comment by namsor** [comment]
Hi Synthapy,
NamSor Origin API is the API to guess the likely country of origin, with a confidence level. See
http://api.namsor.com/
Best,
E.
